### ISSUE TITLE
Improve transactions verification process in `WithVerifyBlock` dBFT callback

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#127]
After https://github.com/bane-labs/go-ethereum/pull/87 there's a proper `WithVerifyBlock` dBFT callback implemented. During block verification it performs basic transactions correctness checks (while processing transactions states):
https://github.com/bane-labs/go-ethereum/blob/d1dd2994df381057c4e4c66dcf497c0a8d7978ee/core/state_processor.go#L90-L93
and
https://github.com/bane-labs/go-ethereum/blob/d1dd2994df381057c4e4c66dcf497c0a8d7978ee/core/state_processor.go#L113-L117
and https://github.com/bane-labs/go-ethereum/blob/d1dd2994df381057c4e4c66dcf497c0a8d7978ee/core/state_transition.go#L174-L183
and
https://github.com/bane-labs/go-ethereum/blob/d1dd2994df381057c4e4c66dcf497c0a8d7978ee/core/state_transition.go#L342-L364

So basic checks for proposed in-block transactions are there and seems that we don't need a separate mempool to verify in-block transactions. But, there should be some policy checks implemented, as @chenquanyu mentioned in https://github.com/bane-labs/go-ethereum/pull/87#issuecomment-1920978768.

**Comment by roman-khimov** [comment]
> seems that we don't need a separate mempool to verify in-block transactions

The problem is to get them from peers while creating a block (not going into CV because of missing tx).

**Comment by AnnaShaleva** [comment]
> > seems that we don't need a separate mempool to verify in-block transactions
> 
> The problem is to get them from peers while creating a block (not going into CV because of missing tx).

For this we have a separate designated https://github.com/bane-labs/go-ethereum/issues/98#issuecomment-1919591698.  And this issue is about additional in-block transactions verification.

**Comment by AnnaShaleva** [comment]
Replaced by #314, not relevant anymore.
