### ISSUE TITLE
governance:  burning fees function.

### ISSUE THREAD

**Issue by chenquanyu** [bane-labs/go-ethereum#163]
We have not yet added the function of burning fees. We can send part of fees to an empty address in the governance contract to burn and configure this burning ratio in the policy contract.

_Originally posted by @chenquanyu in https://github.com/bane-labs/go-ethereum/issues/7#issuecomment-2049059397_

**Comment by roman-khimov** [comment]
Can we do that in T3? While simple, burning is an important part of the project economics to me.
