### ISSUE TITLE
Add documentation about NeoX node start

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#175]
# Rationale

Although almost no changes were made in the node configuration flags, we're currently missing NeoX node start guide.

# Implementation

We need to adjust the README.md to reflect the relevant NeoX node information. We also need to add a documentation about how to start the NeoX node and join the testnet (and mainnet in future).

**Comment by AnnaShaleva** [comment]
We also need to adjust the hardware requirements section of README.md, likely for Neo X needs we don't a lot for the first time.

**Comment by txhsl** [comment]
I think we have some documents https://docs.banelabs.org/development/running-a-node-in-testnet.
