### ISSUE TITLE
Add Native Treasury

### ISSUE THREAD

**Issue by mialbu** [bane-labs/go-ethereum#183]
Based on some conversations in the Bridge Contract Repo (e.g., [here](https://github.com/bane-labs/bridge-evm-contracts/issues/37) and this following [issue](https://github.com/bane-labs/bridge-evm-contracts/issues/74)), it'd be preferred to have a treasury contract instead of the bridge contract holding most of the initial allocation in the genesis.

This treasury will be highly sensitive, and should have the single purpose of funding the bridge. I suggest the following for the treasury contract:

1. it'll be a native contract holding all* of the initial Gas allocation
2. it'll only have a single method that sends Gas to the bridge proxy
3. invoking this method requires a vote from the Neo X Governance
4. it should (not) be upgradeable (?)

*except for some other needed initial allocations, e.g., the bridge relayer, some starting allocation for the bridge, etc.

**Context from Bridge Contracts Development**
- The bridge management introduced a new role `funder` in https://github.com/bane-labs/bridge-evm-contracts/pull/79.
- The bridge now has a `receive` function that is restricted only to this `funder` role. It will be the only address that is allowed to send Gas to the bridge via simple transfer.
- This new role `funder` is intended to be set to the above described native treasury contract.

Please provide some feedback/input about the above suggestion and also whether it should be upgradeable. In the meantime, I'll draft an implementation for a native treasury contract and will open a PR for it.

@steven1227 @AnnaShaleva @roman-khimov @gsmachado

**Comment by gsmachado** [comment]
Due to safety and risk purposes, I strongly recommend to implement this.

**Comment by mialbu** [comment]
I've committed a draft implementation for this in #184.
