### ISSUE TITLE
Solve the broadcast problem of pending transactions under traffic and unstable connections

### ISSUE THREAD

**Issue by txhsl** [bane-labs/go-ethereum#193]
# Rationale

There is a widely-addressed issue of Geth, please refer to https://github.com/ethereum/go-ethereum/issues/22308. The problem is, some transactions may keep pending but never get mined when there is a traffic or the network connection is not stable.

Because the node will only broadcast a transaction once after the memory pool accepts it, so it is possible that the node mark a transaction as “broadcasted” but CNs don't receive it.

We don't allow local transactions on RPC nodes (now on T3), so there is no way to rebroadcast pending transactions (e.g. reboot).

This issue can be eased by increasing the amount of node connections, but it still exists.

# Implementation

Geth has never fixed this, but BSC tried with https://github.com/bnb-chain/bsc/pull/570, by allowing to set up a regular rebroadcast for local pending transactions. We may need a similar or the same thing.

**Comment by roman-khimov** [comment]
NeoGo has retransmission implemented, we can port this mechanism here.
