### ISSUE TITLE
GVN-02 - Missing Storage Gaps in Upgradable Contracts `[Medium]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/go-ethereum#198]
<p>In <strong>NeoX</strong> governance contracts, the Universal Upgradeable Proxy Standard (UUPS) functionality is used to enable future upgrades. However, it has been observed that the base contracts lack reserved storage variables (<code>__gap</code>), a recommended practice in the design of upgradeable contracts. This design omits a crucial component to prevent overwriting of state variables in future contract updates.</p>
<p>Storage gaps serve as a convention to allocate storage spaces within a base contract, ensuring future versions can use these spaces without impacting the storage layout of child contracts.</p><p>The lack of reserved storage variables may lead to storage conflicts when new state variables are introduced in future contract versions. Solidity's state storage layout is sequential and rigid, and any new variables will be aligned directly after the last existing ones. Without reserved storage spaces (<code>__gap</code>), there is a risk of overwriting existing memory locations.</p>

**Remediation:**
<ul><li><p>Introduction of <code>__gap</code> variables:<strong> </strong>Modify base contracts to include reserved<strong> </strong><code>__gap</code> storage variables, appropriately sized to allow future expansion of the contract without affecting existing state variables. These variables act as buffers between variable definitions to prevent unintentional overwrites.</p></li><li><p>Maintain detailed and up-to-date documentation of the contract storage structure, including the position and purpose of each variable and the reserved <code>__gap</code> spaces. This will make it easier to safely manage future updates and help avoid critical errors in storage layout.</p></li></ul>

**References:**
- https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#storage-gaps

**Source references:**
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L8">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L8</a></p>

**Comment by txhsl** [comment]
@chenquanyu

**Comment by txhsl** [comment]
Considering the contract storage compatibility with deployed NeoX T3, this change is not planned.
