### ISSUE TITLE
GVN-04 - Uninitialized Governance Variables `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/go-ethereum#200]
<p>The presence of multiple uninitialized critical variables has been detected in the <code>Governance.sol</code> contract, which are part of the<strong> NeoX </strong>governance infrastructure. These variables (<code>consensusSize</code>, <code>minVoteAmount</code>, <code>voteTargetAmount</code>, <code>registerFee</code> and <code>epochDuration</code>) are essential for the operability and correct functioning of the governance system. The absence of initialization and methods for their configuration results in these values remaining zero, which means that the governance system will not function as intended.</p><p>It has been considered to eliminate this issue due to the operation of Bane itself, where the mentioned values are initialized at the genesis of the blockchain. However, because the contract code can be reused, or even updated afterwards, it has been decided to be kept as a briefing note for the development team. Furthermore, being able to establish these values would facilitate the creation of unit tests.</p>
<p>Contracts must have a <code>constructor</code> in which these values ​​are established, or in the case of updateable contracts, an <code>initialize</code> method that fulfills this function.</p><p>The lack of appropriate values ​​in these variables not only prevents the normal execution of governance functions, but also exposes the system to significant security and functionality risks. For example, without an appropriate <code>minVoteAmount</code>, votes could be recorded without minimum participation guarantees, affecting the legitimacy of the decisions made. Similarly, an <code>epochDuration</code> not properly configured could result in irregular or indefinite voting periods, disrupting the entire governance cycle.</p>

**Remediation:**
<ul><li><p><strong>Initialization during deployment:</strong> Modify the contract to include a constructor or in the case of updatable contracts, an initialization function that sets safe and reasonable default values ​​for all critical variables during contract deployment. This ensures that the contract begins its operation with a defined and predictable state.</p></li><li><p><strong>Secure configuration methods:</strong> Implement administrative functions that allow the configuration of these post-deployment variables. These features should be protected by access controls so that only authorized users (such as administrators or through a voting mechanism) can modify them.</p></li><li><p><strong>Integrity validations: </strong>Incorporate checks into functions that depend on these values ​​to ensure that they operate within expected parameters. For example, verify that <code>epochDuration</code> and <code>minVoteAmount</code> are not zero before proceeding with voting and consensus calculation operations.</p></li></ul>

**Source references:**
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L65-L73">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L65-L73</a></p>

**Comment by txhsl** [comment]
They are initialized in the genesis block allocation. Plz refer to https://github.com/bane-labs/go-ethereum/blob/bane-main/config/genesis_testnet.json.

The codes of these system contracts are not deployed but directly setted, so constructors will not be executed.
