### ISSUE TITLE
GVN-05 - GAS Optimizations `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/go-ethereum#201]
<p>Software optimization is the process of modifying a software system to make an aspect of it work more efficiently or use less resources. This premise must be applied to smart contracts as well, so that they execute faster or in order to save GAS.</p><p>On EVM blockchain, GAS is an execution fee which is used to compensate miners for the computational resources required to power smart contracts. If the network usage is increasing, so will the value of GAS optimization.</p><p>These are some of the requirements that must be met to reduce GAS consumption:</p><ul><li><p>Short-circuiting.</p></li><li><p>Remove redundant or dead code.</p></li><li><p>Delete unnecessary libraries.</p></li><li><p>Explicit function visibility.</p></li><li><p>Use of proper data types.</p></li><li><p>Use hard-coded constant instead of state variables.</p></li><li><p>Avoid expensive operations in a loop.</p></li><li><p>Pay special attention to arithmetical operations and comparisons.</p></li></ul>
<h4>Avoid Compound Assignment Operator</h4><p>It is recommended to avoid using compound assignment operators (for example, <code>+=</code>, <code>-=</code>, <code>*=</code>, etc.) on state variables. Compound assignment operators in Solidity require multiple steps to execute and can result in increased gas costs compared to simple assignment, like <code>var = var + x</code>.</p><p>By avoiding compound assignment operators and using simple assignment instead, it is possible to reduce gas costs, making the project more efficient.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L143" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L143</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L170" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L170</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L229-L231" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L229-L231</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L281" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L281</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L419" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L419</a></p></li></ul><h4>Logic Optimization</h4><p>The <code>_computeReward</code> method initializes the local variables <code>height</code>, <code>lastGasPerVote</code> and <code>latestGasPerVote</code>. However, it immediately follows with a conditional statement. If this condition is not met, the method returns 0 directly without using the previously declared variables.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/1c9eb813-16ae-45be-bd39-c9148c10f2d5)

<p>It is advisable to perform the check before declaring all the variables, in order to optimize the gas consumption of the method as much as possible in the event that the Epoch has not finished.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L340-L341" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L340-L341</a></p></li></ul><p>In the <code>registerCandidate</code> and <code>exitCandidate</code> methods, the contains method of the candidateList set is used to check whether a candidate already exists before adding or removing it. By reusing the <code>boolean</code> return from the call to the <code>add</code> and <code>remove</code> methods, which returns whether it was processed correctly. Therefore, it is possible to save gas by eliminating the <code>contains</code> check.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/2f920ede-80e8-4eee-b531-6dd2106a3907)

<h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L168" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L168</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L182" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L182</a></p></li></ul><p>The <code>checkVote</code> function performs a full run over <code>voters</code> to count how many have voted. The problem is that the <code>for</code> loop continues even after the necessary number of votes has already been reached in order to consider the vote successful.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/a519f8a3-98a9-4d9c-a4af-906013cca1a2)

<p>It is advisable to introduce a conditional inside the <code>for</code> loop in order to stop its execution as soon as the necessary threshold of votes has been reached. This not only reduces gas consumption but also optimizes the execution time of the function.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L53" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L53</a></p></li></ul><h5>Use Constants in needVote</h5><p>It has been observed that calls to the <code>needVote</code> modifier redundantly calculate hashes with static values, resulting in excessive gas consumption during transactions.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/82f73b6d-5362-4dc7-85fd-21e33315dbea)

<p>It is recommended to previously calculate the hash values ​​of these constant values ​​within the contract.Therefore, these values ​​can be accessed without the need to recalculate them on each call to the modifier, thus reducing gas consumption and improving the overall efficiency of the contract.</p><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Policy.sol#L55" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Policy.sol#L55</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Policy.sol#L67" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Policy.sol#L67</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Policy.sol#L79" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Policy.sol#L79</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Policy.sol#L55" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Policy.sol#L94</a></p></li></ul><h4>Duplicate External Contract Calls</h4><p>An inefficiency has been detected in the contract's <code>needVote</code> modifier, which makes three calls to the <code>getMinners</code> function through different methods. This practice results in redundant use of resources which triggers an increase in gas consumption.</p><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L56" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L56</a></p></li></ul><h4>Increase Operation Optimization</h4><p>During the audit it was found that it is possible to optimize all the <code>for</code> loops in the project.</p><p><br/>There are two main ways to increment a variable in solidity:</p>

```
++i will increment the value of i, and then return the incremented value.
i++ will increment the value of i, but return the original value that i held before being incremented.
```

<p>Since the return of the increment operation of the <code>for</code> loop is indifferent and discarded, both <code>i++</code> or <code>++i</code> instructions are completely valid instructions. However, the <code>++i</code> instruction has a considerably lower cost compared to incrementing a variable using <code>i++</code>, for this reason it is convenient to use <code>++i</code> for the increments of the for loops.</p><p><br/>An example of this behavior can be seen below:</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/4eb43b48-e14f-4a13-bd35-4fda1636184a)

<h5>References</h5><ul><li><p><a href="https://docs.soliditylang.org/en/latest/types.html#compound-and-increment-decrement-operators" rel="noopener noreferrer nofollow" target="_blank"><u>https://docs.soliditylang.org/en/latest/types.html#compound-and-increment-decrement-operators</u></a></p></li></ul><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L22" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L22</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L37" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L37</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L48" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L48</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L50" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L50</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L141" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L141</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L377" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L377</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L386" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L386</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L315" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L315</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L398" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L398</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L401" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L401</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L419" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L419</a></p></li></ul><h4>Caching Arrays Length in Loops</h4><p>Every time an array iteration occurs in a loop, the solidity compiler will read the array's length. Thus, this is an additional <code>sload</code> operation for storage arrays (100 more extra gas for each iteration except for the first) and an additional <code>mload</code> action for memory arrays (3 additional gas for each iteration except for the first).</p>

```
for (uint i; i < array.length; ++i) {
    // ...
}
```

<p>The array length (in stack) might be cached to reduce these additional costs:</p>

```
uint length = array.length;
for (uint i; i < length; ++i) {
    // ...
}
```

<p><br/>The <code>sload</code> or <code>mload</code> action is only performed once in the example above before being replaced by the inexpensive <code>dupX</code> instruction.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L22" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L22</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L37" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L37</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L48" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L48</a></p></li></ul><h4>Dead Code</h4><p>In programming, a part of the source code that is never used is known as dead code. The execution of this type of code consumes more GAS during deployment, something that is not necessary.</p><p>The <code>safeTransfer</code> method of the <code>TransferHelper</code> library is not used during the execution of the contract, so it would be convenient to either remove it or to use it.</p><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovReward.sol#L7" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovReward.sol#L7</a></p></li></ul>

**Comment by txhsl** [comment]
> The `checkVote` function performs a full run over voters to count how many have voted.

Yes, I had a look at the code, but as an internal function, `checkVote` runs whenever `needVote` is called. So it only returns `true` ASA the `voteCount` reaches the threshold, which means the `for` loop will never run further more than necessary.

**Comment by txhsl** [comment]
- Avoid Compound Assignment Operator (not planned)
- Logic Optimization (completed)
- Use Constants in needVote (completed)
- Duplicate External Contract Calls (completed)
- Increase Operation Optimization (not planned)
- Caching Arrays Length in Loops (completed)
- Dead Code (completed)

**Comment by AnnaShaleva** [comment]
> Avoid Compound Assignment Operator (not planned)
> Increase Operation Optimization (not planned)


@txhsl, I'm not a solidity developer, but is there any specific reason why you haven't implemented these two? They seem to be quite straightforward, and if it helps to improve GAS invocation cost, when why not?

**Comment by txhsl** [comment]
@AnnaShaleva They can save gas, yes. But the code readability is also important.

Operators like `+=`, `-=` and `++` are helpful in making the contract logic clear to read. We can write everything in assembly code to save gas, but it will make things quite hard to understand.

Especially the `++`, we will have to write `i = i + 1` in `for` loops ~~(`++i` starts from 1 not 0)~~, which is not exact the thing we want to see in a business contract.

**Comment by shargon** [comment]
> Especially the ++, we will have to write i = i + 1 in for loops (++i starts from 1 not 0), which is not exact the thing we want to see in a business contract.

Is only for the increment part, so the initial value is not affected.

**Comment by txhsl** [comment]
> Is only for the increment part, so the initial value is not affected.

Oh, yes. But since the bridge side remains the same, I'm not going to modify them as well.

**Comment by chenquanyu** [comment]
I have tested remix with 1000 cycles, the gas cost of `i++` and `++i` is almost the same, `i=i+1` consumes more gas.

``` 
uint256 public number=1;

    function store(uint256 num) public {
        uint j = 0;
        for (uint256 i = 0; i < num; i++) {
            j =j +i;
        }
        number = j;
    }

    function store2(uint256 num) public {
        uint j = 0;
        for (uint256 i = 0; i < num; i=i+1) {
            j =j +i;
        }
        number = j;
    }

    function store3(uint256 num) public {
        uint j = 0;
        for (uint256 i = 0; i < num; ++i) {
            j =j +i;
        }
        number = j;
    }
```

![store](https://github.com/bane-labs/go-ethereum/assets/4393234/86177c82-4cb3-40c2-b235-368d2cf54319)

**Comment by shargon** [comment]
You should test it with different smart contracts because the offset where the method is located is important for the execution cost.

In Solidity, the opcodes for `i++` and `++i` can be different due to the nature of the postfix and prefix increment operations.

1. **Postfix increment (`i++`)**:
   - `DUP1`: Duplicate the top stack item.
   - `PUSH1 01`: Push the value 1 onto the stack.
   - `ADD`: Add the top two stack items.
   - `SWAP1`: Swap the top two stack items.
   - `POP`: Pop the top stack item.

2. **Prefix increment (`++i`)**:
   - `PUSH1 01`: Push the value 1 onto the stack.
   - `ADD`: Add the top two stack items.

The primary difference is that `i++` involves additional stack operations to maintain the original value of `i` for the expression's use, while `++i` increments the value directly and returns it.

**Comment by chenquanyu** [comment]
I also tested in different contract, they are almost the same. Maybe the compiler optimized the code. I used Enable optimization 200 config.
```
contract Storage1 {
    function sum(uint256 num) public pure returns (uint) {
        uint j = 0;
        for (uint256 i = 0; i < num; i++) {
            j =j +i;
        }
        return j;
    }
}

contract Storage2 {
    function sum2(uint256 num) public pure returns (uint) {
        uint j = 0;
        for (uint256 i = 0; i < num; ++i) {
            j =j +i;
        }
        return j;
    }
}
```
![sum](https://github.com/bane-labs/go-ethereum/assets/4393234/aef82355-c339-4ea4-be7e-8a2989bda71d)

**Comment by shargon** [comment]
Then the optimizer did his work :)
