### ISSUE TITLE
GVN-07 - Code Quality `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/go-ethereum#203]
<p>It has been possible to verify that, despite the good quality of the code, there is a lack of order and structure that makes reading and analyzing the code difficult. This is a very bad practice, especially in these types of projects that are continually changing and improving.</p><p>High-quality code is important for various reasons, including maintainability, reliability, efficiency, scalability, and security. Well-written code that adheres to best practices offers several advantages, such as easier to maintain and extend, less prone to errors, more efficient, improved collaboration potential, scalability, and heightened security. Ultimately, good code quality contributes to a more dependable, maintainable, and secure software product, improving the overall user experience while reducing the risk of introducing new vulnerabilities.</p>
<h4>Improvable Dependencies</h4><p>It has been noted that the <code>ERC1967Proxy</code> library has been included directly in the project code instead of being managed as an external dependency. This approach increases contract size and can lead to code duplication, especially if multiple contracts within the same project use the same library. In addition, it complicates the updating and maintenance of the code, since any change in the library requires a recompilation and a new deployment of the affected contracts.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/ERC1967Proxy.sol" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/ERC1967Proxy.sol</a></p></li></ul><p>The <code>Governance.sol</code> contract implements the <code>ReentrancyGuard</code> dependency of the OpenZeppelin standard library in its non-updatable version. For contracts designed to be upgradeable, it is recommended to use <code>@openzeppelin/contracts-upgradeable</code>, which includes a version of <code>ReentrancyGuard</code> specifically designed to be used with upgradeable proxies.</p><h5>Source Code References</h5><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L5" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L5</a></p><h4>Unsafe Cast</h4><p>In the <code>_topK function</code>, a value of type <code>int</code> is cast to <code>uint</code> in an unsafe manner. This cast can lead to unwanted behavior or errors at runtime, especially if the value of <code>int</code> is negative, in case the contract is incorrectly initialized.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/0649c807-1e66-4fb8-9b7d-9da406ba8611)

<h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L399" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L399</a></p></li></ul><h4>Avoid Duplicate Code</h4><p>The <code>_safeTransferETH</code> method of the <code>Governance</code> contract is already included in the existing <code>TransferHelper</code> library in the <code>GovReward.sol</code> file. Therefore, it is convenient to reuse the library, and avoid duplicating code, which will make it more complicated to maintain.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L367" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L367</a></p></li></ul><h4>Use of Selector</h4><p>In the current <code>safeTransfer</code> function, a hard-coded function selector (<code>0xa9059cbb</code>) is used to interact with the <code>transfer</code> method. Although this is functional, it does not provide transparency into the operation being performed, making the code difficult to read, maintain, and audit.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/7fa3f75d-059d-45f1-8d22-8054a2fb5865)

<p>Using hard-coded selectors can make the code less readable and more difficult to verify, especially for people who are not familiar with the specifics of function selectors. To improve code clarity and maintainability, it is recommended to use <code>IERC20.transfer.selector</code>, which automatically generates the function selector based on the interface declaration.</p><h5>References</h5><ul><li><p><a href="https://github.com/Uniswap/v3-periphery/blob/main/contracts/libraries/TransferHelper.sol#L34" rel="noopener noreferrer nofollow" target="_blank">https://github.com/Uniswap/v3-periphery/blob/main/contracts/libraries/TransferHelper.sol#L34</a></p></li></ul><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovReward.sol#L10" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovReward.sol#L10</a></p></li></ul><h4>Improvable Event Emit</h4><p>The <code>_settleReward</code> function emits the <code>VoterClaim</code> event every time a reward is calculated and assigned, regardless of whether the reward value is zero. This can lead to unnecessary emission of events, which not only consumes gas but can also generate noise in the event logs, complicating data analysis and contract monitoring.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/7dbbd148-31eb-4423-93be-e302165b958d)

<p>It is recommended to modify the <code>_settleReward</code> function so that it only raises the <code>VoterClaim</code> event when the reward is non-zero. This change ensures that events are only emitted when there is a significant status update, optimizing gas usage and improving log interpretation.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L363" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L363</a></p></li></ul><h4>Solidity Literals</h4><p>Although the use of exponential literals is technically correct and does not directly affect contract performance, it can compromise how the code is read and understood, in order to make the code easier to read and to minimize human errors. Solidity recommends the use of literals which consequently makes it more user friendly. Additionally, readability is crucial to avoid errors and facilitate code auditing and validation.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/45d8ffbb-43f1-4d6b-8c08-8c42824cc1fe)

<h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L63" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L63</a></p></li></ul><h4>Improvable Contract Structure</h4><p>Interfaces and libraries are currently being included within the contracts themselves instead of keeping them in separate files. This mixture of contract and interface definitions in a single file can complicate the maintainability and clarity of the code, which is why it is a totally discouraged practice.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L4-L6" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L4-L6</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovReward.sol#L6-L33" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovReward.sol#L6-L33</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L8-L50" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L8-L50</a></p></li></ul><h4><br/>Improve Nomenclature on Internal Methods</h4><p>In Solidity, it is common practice to use an <code>underscore (_)</code> at the beginning of internal function names to distinguish them from public or external functions. This helps clarify feature visibility and ensures that code is more readable and maintainable, particularly in large and complex contracts.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/912e3a81-bf24-46da-b682-74daaec0741c)

<p>Adopting this naming convention does not directly impact contract performance or gas consumption, but it significantly improves code readability and reduces the risk of errors, especially in the integration and maintenance of extensive code.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L30" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L30</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L35" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L35</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L42" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L42</a></p></li></ul><h4>Named Mappings</h4><p>Solidity 0.8.18 allows to use named parameters in mapping types. This new feature enables the assignment of descriptive names to mappings, improving the code's readability, interpretation, and audit.</p><h5>Reference</h5><ul><li><p><a href="https://soliditylang.org/blog/2023/02/01/solidity-0.8.18-release-announcement/" rel="noopener noreferrer nofollow" target="_blank">https://soliditylang.org/blog/2023/02/01/solidity-0.8.18-release-announcement/</a></p></li></ul><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L18" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L18</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Policy.sol#L12" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Policy.sol#L12</a></p></li><li><p><a href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L78-L106" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L78-L106</a></p></li></ul>

**Remediation:**
<p>As a reference, it is always advisable to apply coding style and good practices, which can be found in multiples standards such as:</p><ul><li><p>Solidity Style Guide (<a target="_blank" rel="noopener noreferrer nofollow" href="https://docs.soliditylang.org/en/v0.8.24/style-guide.html">https://docs.soliditylang.org/en/v0.8.24/style-guide.html</a>).</p></li></ul><p>These references are very useful to improve the quality of the smart contract. A few of these practices are generally known and accepted forms to develop software.</p>

**Comment by txhsl** [comment]
- Improvable Dependencies (partially completed)
- Unsafe Cast (not planned, `j` is never negative)
- Avoid Duplicate Code (not planned, library removed)
- Use of Selector (not planned, code removed)
- Improvable Event Emit (not planned)
- Solidity Literals (not planned)
- Improvable Contract Structure (completed)
- Improve Nomenclature on Internal Methods (completed)
- Named Mappings (not planned)
