### ISSUE TITLE
GVN-09 - Reentrancy Pattern `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/go-ethereum#205]
<p>The Reentrancy attack is a vulnerability that occurs when external contract calls can make new calls to the calling contract, before the initial execution is completed. For a function, this means that the state of the contract could change in the middle of its execution as a result of a call to an untrusted contract or the use of a low-level function with an external address.</p><p>One way to mitigate this vulnerability is to use a checks-effects-interactions pattern in the contract design. In this pattern, the contract first performs all the necessary checks to ensure that the function call is valid and then performs all the state changes before interacting with other contracts or accounts.</p>
<p>In the case of the <code>needVote</code> modifier of the <code>GovernanceVote</code> contract, votes are cleared after external calls are made, so the call can be redirected to any<em> </em>method before updating the values.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/175f67f4-d136-4b1d-84f3-2270bb8d5888)

<p>By applying the security measures described, the contract can ensure that it completes all state changes before allowing any external interactions, preventing reentrancy and other types of attacks in smart contracts.</p>

**Remediation:**
<p>It is <strong>essential to always make the state changes in the storage before making transfers or calls to external contracts</strong>, in addition to implementing the necessary measures to avoid duplicated calls or chain calls to the methods. A good practice to avoid reentrancy is to organize the code according to the following pattern:</p><ol><li><p>The first step is conducting all necessary <strong>checks</strong>.</p></li><li><p>The next step is the application of all <strong>effects.</strong></p></li><li><p>All external <strong>interactions</strong> take place in the last step.</p></li></ol>

**References:**
- https://docs.soliditylang.org/en/latest/security-considerations.html#use-the-checks-effects-interactions-pattern
- https://fravoll.github.io/solidity-patterns/checks_effects_interactions.html

**Source references:**
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L66-L68">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/GovernanceVote.sol#L66-L68</a></p>

**Comment by txhsl** [comment]
Yes, it doesn't cause problems temporally, but possible in future.
