### ISSUE TITLE
Rework voter reward distribution scheme for `transferVote`

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#222]
The problem is described in https://github.com/bane-labs/go-ethereum/pull/182#discussion_r1576317119.

We need to decide on the desired behaviour (both cases are technically valid).

**Comment by txhsl** [comment]
The same as I described in #219, I'd close that one.

**Comment by AnnaShaleva** [comment]
> The same as I described in https://github.com/bane-labs/go-ethereum/issues/219, I'd close that one.

Oh, sorry, I've missed that issue.

**Comment by txhsl** [comment]
I'm going to allow immediate voter distribution if possible.

After a discussion with @steven1227 and @chenquanyu, the current scheme forces a lock in voter operation when DKG, and now only I'm against this. So let's switch to another solution, the same as N3, and remove the governance lock.
