### ISSUE TITLE
Ensure Solidity compiler ^0.8.25 is compatible with dBFT-supported hardforks

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#224]
Ref. https://github.com/bane-labs/go-ethereum/pull/208#discussion_r1620928382, ref. https://github.com/bane-labs/go-ethereum/issues/206. We can't update compiler version without the dBFT compatibility check.

**Comment by txhsl** [comment]
It depends on #189, currently T3 doesn't support opcode `MCOPY`. But we can make the compiler work by specifying the target EVM version.
