### ISSUE TITLE
Black listed Policy feature is not used by Governance

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#239]
#### Expected behaviour

Addresses marked as "blackListed" in Policy system contract should be banned from:
* calling contracts, deploying contracts, transferring funds (this may be unified in the implementation by blocking transactions with blocked sender)
* elections in consensus members (this may be implemented exactly like in N3: all addresses are allowed to be registered as a candidate, but only non-blocked addresses are returned from `getCandidates` call and be elected as CN, see https://github.com/nspcc-dev/neo-go/blob/0f2229d6a5e65f1e5608e1ed2ebb1e9e59c5c6c3/pkg/core/native/native_neo.go#L1024).

#### Actual behaviour

Address may be blocked/unblocked via Policy system contract interface. But it does not affect any operations on the network. Right now Policy's "blackListed" addresses are no more than records in the contract.

**Comment by AnnaShaleva** [comment]
@txhsl, @steven1227, @chenquanyu  I'm not sure if we should include this into T4, what do you think? But it definitely needs to be included into mainnet version.

**Comment by txhsl** [comment]
I think I have implemented this in transaction validation and state transition in #6.

**Comment by chenquanyu** [comment]
https://github.com/bane-labs/go-ethereum/blob/cada98a3fa21eda3d8295a3e0f491c1b6674014f/core/state_transition.go#L304

**Comment by AnnaShaleva** [comment]
> I think I have implemented this in transaction validation and state transition

Yes, you're right, I missed that usage. So the first point is not a problem. But how about the second problem? It seems to me that blocked accounts are still allowed to be elected as CN.

**Comment by txhsl** [comment]
> It seems to me that blocked accounts are still allowed to be elected as CN.

Yes, I can add this check to Governance `onPersist()`.

**Comment by AnnaShaleva** [comment]
> Yes, I can add this check to Governance onPersist().

Good, and probably `_computeConsensus` should be adjusted.
