### ISSUE TITLE
[suggestion] add `_disableInitializers` to every UUPS impl contract's constructor 

### ISSUE THREAD

**Issue by dusmart** [bane-labs/go-ethereum#257]
# Rationale

The bridge contract is already using `initialize` for UUPS contract's initialisation and calling `_disableInitializers()` in the impl contract's constructor now. https://github.com/bane-labs/bridge-evm-contracts/pull/141

If we have to upgrade a contract one day, we <del>'ll have to</del> may change to use this pattern, too. I suggest that we introduce this into our contracts now so that the new contracts will also have these settings in their code.

# Implementation

See openzepplin's documents [here](https://docs.openzeppelin.com/contracts/4.x/api/proxy#UUPSUpgradeable).

> Avoid leaving a contract uninitialized.
>
> An uninitialized contract can be taken over by an attacker. This applies to both a proxy and its implementation contract, which may impact the proxy. To prevent the implementation contract from being used, you should invoke the [_disableInitializers](https://docs.openzeppelin.com/contracts/4.x/api/proxy#Initializable-_disableInitializers--) function in the constructor to automatically lock it when it is deployed:
> ```
> /// @custom:oz-upgrades-unsafe-allow constructor
> constructor() {
>     _disableInitializers();
> }
> ```

**Comment by AnnaShaleva** [comment]
Confirmed by @txhsl.

**Comment by gsmachado** [comment]
@mialbu can you explain what was our approach for the bridge contracts?

**Comment by mialbu** [comment]
> @mialbu can you explain what was our approach for the bridge contracts?

It's the suggested way (by OZ) to disallow any initializing logic on the logic contract itself (see [here](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#initializing_the_implementation_contract)).
