### ISSUE TITLE
invalid totalVotes during transferVote if candidateFrom is deactivated

### ISSUE THREAD

**Issue by dusmart** [bane-labs/go-ethereum#258]
See different votes updating logic here for `vote` and `revokeVote` as well as `transferVote`.

https://github.com/bane-labs/go-ethereum/blob/6049e3db040262041b099a0d8040937541f516e5/contracts/solidity/Governance.sol#L174-L177

https://github.com/bane-labs/go-ethereum/blob/6049e3db040262041b099a0d8040937541f516e5/contracts/solidity/Governance.sol#L195-L202

https://github.com/bane-labs/go-ethereum/blob/6049e3db040262041b099a0d8040937541f516e5/contracts/solidity/Governance.sol#L222-L227

It's obvious that `transferVote` is a combination of `revokeVote` and `vote`. But the logic above is sligtly different from the combination.

If the candidateFrom was not in candidateList, we should add the votedAmount of msg.sender to totalVotes.

My suggestion is to delete transferVote directly. Another alternative method is to just make `transferVote == revokeVote + vote`. Let's keep safety first priority and then consider the GAS cost.

**Comment by dusmart** [comment]
If `nonReentrant` makes it hard to implement `transferVote == revokeVote + vote`.
A possible way is to define a private `_vote` and private `_revokeVote`. Then let `vote == _vote` and `revokeVote = _revokeVote` as well as `transferVote == _revokeVote + _vote`. Then make all of these three external method `nonReentrant`.

**Comment by txhsl** [comment]
Confirmed, but I just fixed the vote counter.
