### ISSUE TITLE
Ensure Geth metrics are reachable

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#264]
An attempt to query node metrics with recommended node configuration mentioned in README leads to:
```
(13:04:01)[sergio@themis:~]% curl http://localhost:6060/metrics
404 page not found
(13:04:05)[sergio@themis:~]% curl http://localhost:6060        
404 page not found
```

We need to ensure that node metrics are reachable and find a way to properly configure them to enable node monitoring.

**Comment by txhsl** [comment]
The metrics url might be `http://localhost:6060/debug/metrics`. :)

**Comment by AnnaShaleva** [comment]
Confirmed, thanks!
