### ISSUE TITLE
Add amev key local persistence

### ISSUE THREAD

**Issue by txhsl** [bane-labs/go-ethereum#310]
Ref https://github.com/bane-labs/go-ethereum/pull/301#discussion_r1729314256.

**Comment by AnnaShaleva** [comment]
Once implemented, within the scope of this issue we also need to remove RLP serialization code that is added by #287 for TPKE testing purposes:
https://github.com/bane-labs/go-ethereum/blob/9468476ec5ebdfbb5a7cff3de22e0772df6639f9/core/antimev/keystore.go#L72
https://github.com/bane-labs/go-ethereum/blob/9468476ec5ebdfbb5a7cff3de22e0772df6639f9/core/antimev/keystore.go#L88

These two methods, all nested RLP serializers and keystore decoder from pure unencrypted file should not be needed anymore if we have proper persistence for aMEV keystore
