### ISSUE TITLE
Shut down Geth gracefully

### ISSUE THREAD

**Issue by nicolegys** [bane-labs/go-ethereum#32]
https://github.com/bane-labs/go-ethereum/blob/fd059099a26002fa053bac14a6ce42c7d671a338/Makefile#L142
The database can be corrupted if we kill the geth instance.

![image](https://github.com/bane-labs/go-ethereum/assets/43694095/9d9de5bc-b4c9-4281-b50f-d960b4845093)

We can use `SIGINT` or some other options.

**Comment by AnnaShaleva** [comment]
Nice catch, I'll check it.

**Comment by nicolegys** [comment]
FYI.

When using a shutdown command such as `kill -INT`, the consensus node will write all relevant information into the database.
![1700819487198](https://github.com/bane-labs/go-ethereum/assets/43694095/6c93c89c-16fd-47e5-97d8-d0ebc4881c25)

Then restart, it can load the most recent block and keep going, instead of waiting for `Inserted known block...`
![1700819971573](https://github.com/bane-labs/go-ethereum/assets/43694095/4bb05ee7-8d3b-48ce-8bc1-86419cda8410)

But I'm confused that, I use the same command to shutdown node2. However, the node2 process never ends after blockchain stopped, it just keep `looking for peers`.
![1700820706642](https://github.com/bane-labs/go-ethereum/assets/43694095/000a86b2-bb2e-4406-b41a-1590bfb48ff2)
