### ISSUE TITLE
Remove `NeoXBurn` fork

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#322]
# Rationale

`NeoXBurn` fork is enabled from 0 in T4/Mainnet, and T3 is dropped. This fork is kind of "transiition" and it's not needed anymore.

# Implementation

Remove `NeoXBurn` from the node configuration, move its logic out of the fork. It should be a default node behavior.

**Comment by txhsl** [comment]
Seems good.

**Comment by AnnaShaleva** [comment]
We should add corresponding instructions on how to overwrite genesis configuration to the release notes, because this change is breaking for the node's database.
