### ISSUE TITLE
Add a `NeoXDKGBlock` setting to enable DKG before Anti-MEV dBFT

### ISSUE THREAD

**Issue by txhsl** [bane-labs/go-ethereum#345]
# Rationale

The current `NeoXAMEVBlock` setting enables the Anti-MEV feature in dBFT. For the Privnet, we have preset keystore files to support this feature, but for Testnet and Mainnet, we need a successful round of DKG before this height, otherwise no secret is shared and usable.

# Implementation

1. Add a `NeoXDKGBlock` height before `NeoXAMEVBlock`;
2. Enable new precompiles and the `KeyManagement` contract from `NeoXDKGBlock`;
3. Still Enable Anti-MEV dBFT from `NeoXAMEVBlock`.

**Comment by vncoelho** [comment]
That is correct, it would be good to use a preset logic that can also be triggered on privnet. Then we just reuse this code here later there instead of precreated shares.

**Comment by txhsl** [comment]
> That is correct, it would be good to use a preset logic that can also be triggered on privnet. Then we just reuse this code here later there instead of precreated shares.

Yes, we will use the same automatic DKG logic for privnet as in production, as well as the fork upgrade process. But since we don't have a friendly interface for data encryption so far, some easy tests will be not practical, especially the following one. 
https://github.com/bane-labs/go-ethereum/blob/8978c4597fc8f9901015812841c2972e59695b47/privnet/README.md?plain=1#L333-L343
