### ISSUE TITLE
performance test: many "missing tx" and "check prepare: some transactions are missing" messages appear in the log when sending txs to cn nodes in parallel

### ISSUE THREAD

**Issue by songb2** [bane-labs/go-ethereum#348]
#### System information

Geth
Version: 0.2.2-stable
Git Commit: 0ee430760eb6aa9bf097a20585597eb6072fe20c
Architecture: amd64
Go Version: go1.22.2
Operating System: linux

#### Expected behaviour
36000 txs should be processed correctly, because I tested that the single seed node can process them in 68 minutes.

#### Actual behaviour

When sending 6000 txs to each consensus nodes in parellel, during processing

1. it will stop producing new blocks at intervals, for example:

 it took 5 minutes from block 1100507 to 1100508
 it took 11 minutes from block 1100508 to 1100509
 and there are a lot of abnormal logs:
```
2024-11-11T10:48:19.441Z	DEBUG	dbft@v0.2.0/check.go:9	check prepare: some transactions are missing	{"hashes": 
...
2024-11-11T10:56:47.818Z	INFO	dbft@v0.2.0/dbft.go:358	missing tx	{"count": 436}
WARN [11-11|10:56:47.849] Unexpected transaction delivery          peer=19bf5a89788f82fac9f7d6b4daabdc03fe4b5b645fcf62dbc8f4cf648b24e87a
WARN [11-11|10:56:47.879] Unexpected transaction delivery          peer=ca1819427cf230c16e6a590f7f1902a1dc9b99dfe0bca675e95ba9fafc837688
WARN [11-11|10:56:47.885] Unexpected transaction delivery          peer=9913c93bdf9359e882c86a4e25c7bf572adda5206cf1c53638df65109619529c
WARN [11-11|10:56:47.905] Unexpected transaction delivery          peer=d364feb20b0d8a60fc6dda11c8bfcfcc66709ec9782fab1076893ffc04952b5c
WARN [11-11|10:56:47.905] Unexpected transaction delivery          peer=adc10be55c135b89c4b91c3f7630e6ecddc1c88cdd55a6d08ce297e0ad5118d8
WARN [11-11|10:56:47.972] Unexpected transaction delivery          peer=7da3f1064d80e1d0ee9d41b1163f9966a7eeb8796e6f527dff6fd634c36c24f1
```
2. 11170 txs were missing

#### Steps to reproduce the behaviour

1. expose consensus nodes' rpc url like the below command (add flag --allow-insecure-unlock, and remove flag --txpool.nolocals):
`./geth --networkid 2407101928 --nat extip:34.30.93.38 --port 30301 --mine --miner.etherbase=fa50a97becd346b242b661891d6b9b6e1073830e --unlock fa50a97becd346b242b661891d6b9b6e1073830e --password nodes/node1/password.txt --authrpc.port 8562 --identity=nodes/node1 --maxpeers=30 --syncmode full --gcmode archive --datadir nodes/node1 --bootnodes enode://c736fedf8ed8c3eaabdeca74b3698a73d3f2d052ab66b2a6102c2664b67b80c8edc43a04207dbbbf7dfc08773c6e912d34222f7eec31ea14d1904d2a733e7575@10.128.0.54:30301 --allow-insecure-unlock --http.api admin,eth,debug,miner,net,txpool,personal,web3,dbft --http --http.addr 0.0.0.0 --http.port 8546 --http.vhosts * --http.corsdomain * --metrics --metrics.addr 0.0.0.0 --metrics.expensive --verbosity 3`
2. prepare the 36000 txs data which can send 0.1 gas to a receiver from 600 wallets and each wallet has 60 txs
3. split the 36000 txs into 6 parts, so each part has 6000 txs
4. send 6000 txs to the 6 different consensus nodes in parallel

#### Backtrace

When submitting logs: please submit them as text and not screenshots.
[node1.log](https://github.com/user-attachments/files/17710767/node1.log)
[node3.log](https://github.com/user-attachments/files/17710771/node3.log)
[node7.log](https://github.com/user-attachments/files/17710818/node7.log)

@AnnaShaleva @txhsl @chenquanyu @steven1227

**Comment by txhsl** [comment]
Just to make the situation clear, @songb2 is trying to evaluate the TPS capability of the 5s-dBFT.

He has tried the combination of 7 CNs and 1 seed node. All transactions were sent to the seed node and the total cost of handling 36000 transactions is about 1 hour.

As far as we know, this result is limited by the mempool reannouncement, and the block space doesn't get fully used.

So he is trying to send transactions to CNs directly.

So I think it's better not to split the transactions, but send the same set to every CN. And the "missing tx" is an expected behavior in your case. @songb2

**Comment by roman-khimov** [comment]
Our standard N3 setup is exactly that, some number of CNs + one RPC with transactions pushed to RPC only. I think it's a bit more realistic than trying to push transactions directly to CNs so I'd recommend keeping it this way.

**Comment by songb2** [comment]
> Just to make the situation clear, @songb2 is trying to evaluate the TPS capability of the 5s-dBFT.
> 
> He has tried the combination of 7 CNs and 1 seed node. All transactions were sent to the seed node and the total cost of handling 36000 transactions is about 1 hour.
> 
> As far as we know, this result is limited by the mempool reannouncement, and the block space doesn't get fully used.
> 
> So he is trying to send transactions to CNs directly.
> 
> So I think it's better not to split the transactions, but send the same set to every CN. And the "missing tx" is an expected behavior in your case. @songb2

I tested that it works correctly if not split the transactions:
total 36000 txs sent to 6 cn nodes, it took 4 minutes, so TPS is 150 tx/s 
each block has txs, the average is 837 txs/block
