### ISSUE TITLE
Support fallback to multisignature block signing scheme

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#352]
# Rationale

#347 introduces transition to threshold block signing scheme starting from NeoXAMEV fork. However, if something goes wrong with TPKE process, then dBFT should be able to fallback to the original multisignature scheme.

# Implementation

1. Include both TPKE shares and simple signatures data to the Commit message.
2. Include "fallback" NextConsensus value into block's Extra data: this field will be used to verify the set of multisignature validator public keys in case of fallback.
3. Include "reserved" NextConsensus into sealing block hash.
4. Check alignment of TPKE indexes from KeyManagement contract with multisignature validator public keys from Governance contract.

**Comment by AnnaShaleva** [comment]
Fallback logic should also take care of reorgs that are possible with the old multisignature scheme, which means that:
1. Sealing proposal awaiting logic should be adjusted to allow mismatch parent hash.
2. PrepareRequest verification callback should be adjusted to save parent with unknown hash.

**Comment by vncoelho** [comment]
What are the rationales or this fallback for now?
how many nodes would need to fail?

As I remember it would be the same threshold as dBFT.

The fallback could be the election of a new committee instead of changing signing scheme.
Inblock emergency committee change, this was also proposed for N3.

**Comment by roman-khimov** [comment]
This mitigates the risks of new DKG and TPKE code, especially DKG ones. It's not related to any thresholds and is purely administrative, restart CNs with an additional parameter --- get ECDSA signatures.
