### ISSUE TITLE
Migrate block signatures onto compressed TPKE public key form

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#355]
# Rationale

Ref. https://github.com/bane-labs/go-ethereum/pull/347#discussion_r1861449326.

# Implementation

The implementation itself is quite straightforward, see 773028baf1de50a68c64e7267867de9af8a5121f. But it needs cache, otherwise it's useless.

**Comment by roman-khimov** [comment]
> But it needs cache, otherwise it's useless.

Not useless, but just slow.
