### ISSUE TITLE
DBFT module error

### ISSUE THREAD

**Issue by nicolegys** [bane-labs/go-ethereum#36]
cannot call dbft functions
![image](https://github.com/bane-labs/go-ethereum/assets/43694095/2379e27b-632d-4713-9dcc-fb3fac91c9af)

**Comment by chenquanyu** [comment]
This issue seems to be only related to "JavaScript console", in http rpc the "dbft_status" can be called when start geth with flag "--http.api dbft". 

![image](https://github.com/bane-labs/go-ethereum/assets/4393234/6005a93f-2dab-4d35-83dd-4ca7a6af27e3)
