### ISSUE TITLE
dbft: geth log has bad block error "Error: invalid extra: invalid NextConsensus retrieved from validators addresses: "

### ISSUE THREAD

**Issue by songb2** [bane-labs/go-ethereum#361]
#### System information

Version: 0.3.0-unstable
Git Commit: 38ad5f32e73525d5c52805eb8f5829a5916a87af
Git Commit Date: 20241211
Architecture: amd64
Go Version: go1.22.2
Operating System: linux

#### Expected behaviour
geth log should contains no error message

#### Actual behaviour
node2 contains the error
```

...

024-12-12T01:26:44.860+0800	DEBUG	dbft@v0.3.2-0.20241205125914-b2ba0cd4b763/dbft.go:231	received message	{"type": "Commit", "from": 5, "height": 2671, "view": 0, "my_height": 2671, "my_view": 0}
2024-12-12T01:26:44.860+0800	DEBUG	dbft@v0.3.2-0.20241205125914-b2ba0cd4b763/dbft.go:231	received message	{"type": "Commit", "from": 5, "height": 2671, "view": 0, "my_height": 2671, "my_view": 0}
WARN [12-12|01:26:44.876] Failed to load old bad blocks            error="pebble: not found"
ERROR[12-12|01:26:44.902] 
########## BAD BLOCK #########
Block: 2671 (0x609c756268870a2a8b82832ab0373944ff1a18f704318253fac9c8d23822d727)
Error: invalid extra: invalid NextConsensus retrieved from validators addresses: expected 0x0d5ace7b2ffd606cad9653b0ae0bc183f5a70017ffe8d746a64ea90e817d1c42, got 0x27c6be0ee0a3d0f72b0abfa3773ef1410dc7ef5c1a6ec108095c67d78fec40c5
Platform: geth (devel) go1.22.2 amd64 linux
VCS: 38ad5f32-20241211
Chain config: &params.ChainConfig{ChainID:2312251829, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:0, LondonBlock:0, ArrowGlacierBlock:0, GrayGlacierBlock:0, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc0006d01e0), NeoXDKGBlock:5, NeoXAMEVBlock:35, CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), DBFT:(*params.DBFTConfig)(0xc0008084c0)}
Receipts: 
##############################

ERROR[12-12|01:26:44.903] Failed to retrieve beacon bounds for bad block reporting err="beacon sync not yet started"
WARN [12-12|01:26:44.904] Synchronisation failed, dropping peer    peer=451dffe330d1085896df2fbb0981f5c727dfe8db2843eacb2664ab41e6146c9c err="retrieved hash chain is invalid: invalid extra: invalid NextConsensus retrieved from validators addresses: expected 0x0d5ace7b2ffd606cad9653b0ae0bc183f5a70017ffe8d746a64ea90e817d1c42, got 0x27c6be0ee0a3d0f72b0abfa3773ef1410dc7ef5c1a6ec108095c67d78fec40c5"
INFO [12-12|01:26:44.904] New block in the chain                   "dbft index"=2671 "chain index"=2671 hash=0x609c756268870a2a8b82832ab0373944ff1a18f704318253fac9c8d23822d727 "parent hash"=0xac977fe748207519f763904fd171727a562073a92b8abfae0ea50a2b37fb9e77 primary=4 coinbase=0x1212000000000000000000000000000000000003 "mix digest"=0x27c6be0ee0a3d0f72b0abfa3773ef1410dc7ef5c1a6ec108095c67d78fec40c5
INFO [12-12|01:26:44.904] Fetching latest sealing proposal         "desired number"=2672

...

```

#### Steps to reproduce the behaviour

run the below command:
`make privnet_start_seven`

[geth_node2.zip](https://github.com/user-attachments/files/18105195/geth_node2.zip)

@AnnaShaleva @txhsl @chenquanyu

**Comment by txhsl** [comment]
Seems like the verification is expecting the old consensus hash to be included in the first block of a new epoch, but the fact is the new one is included.

**Comment by AnnaShaleva** [comment]
It's not the bug, this functionality is not implemented yet. It's the point of https://github.com/bane-labs/go-ethereum/issues/353#issuecomment-2506294546, and currently the node is able to work only with static anti-MEV keystore. I need the final version of #332 to implement proper NextConsensus calculation.

@songb2 what is the height of NeoXDKG and NeoXAMEV forks in your setup?

**Comment by txhsl** [comment]
We are using the 7-node privnet, so they are `5` and `35`.

**Comment by AnnaShaleva** [comment]
Then I'd expect this problem to appear earlier than block 2671. In fact, it should appear after global TPKE public key is updated after NeoXAMEV fork.

**Comment by AnnaShaleva** [comment]
Could you tell when exactly global public key was updated first time after NeoXAMEV fork in your setup?

**Comment by txhsl** [comment]
> Could you tell when exactly global public key was updated first time after NeoXAMEV fork in your setup?

Should be block height `60`, the privnet has no error in 30-block DKG and epoch change, just sometimes a bad block is reported by one of the nodes.

In the log file of this issue, block `2670` started an epoch with successful DKG round `89`, so it was not the first time that global TPKE public key got updated.

**Comment by AnnaShaleva** [comment]
Good, sometimes block arrives via P2P interaction earlier than it's accepted by dBFT, then standard verification code is invoked for this block, which results in bad block reporting. As I said, this problem will be solved by https://github.com/bane-labs/go-ethereum/issues/353#issuecomment-2506294546 implementation, because right now dBFT doesn't support dynamic anti-MEV keystore update:
https://github.com/bane-labs/go-ethereum/blob/2b0bb7a338978b10fc683cc5ff06ac4582e85d0b/consensus/dbft/dbft.go#L2351-L2354
