### ISSUE TITLE
Deal with committee/validators in config

### ISSUE THREAD

**Issue by roman-khimov** [bane-labs/go-ethereum#44]
Seems like we have no committee in Bane, only CNs aka validators. If that's the case (but this needs to be confirmed with the latest governance model) then we should not configure any committee and validators count. Just a set of validators that we can derive the count from easily.

See https://github.com/bane-labs/go-ethereum/pull/40#discussion_r1416146345.

**Comment by steven1227** [comment]
For bane, I believe only validators are necessary.
