### ISSUE TITLE
Change header's Extra format

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#50]
Currently (after #49) header's Extra field have the following format (assuming N validators and M out of N is dBFT honest nodes count):
* 32 bytes reserved for extra vanity, they are a part of sealing data and currently are always empty;
* N validators addresses (each of 20 bytes) that are effectively the full validators set for this block sorted by byte order;
* M validators signatures (each of 65 bytes) sorted by corresponding validators bytes.

We don't need first 32 bytes of Extra to be reserved. We need to change Extra format and replace 32 reserved bytes with a single reserved byte denoting version of Extra. In future we'll be able to change Extra format relying to the first Version byte. The scheme itself is very similar to the Block versioning we currently have in N3. Within the scope of this issue we also need to evaluate compatibility with existing Eth hardforks supported by Geth node (no conflicts with hardforks should happen).

**Comment by roman-khimov** [comment]
Just as an idea --- we can recover the key (and its address) from the signature, so we can have M signatures and N-M addresses (of keys that have not signed the block), then to check the header you can recover the whole set of addresses, sort/dump/hash it and you must get the `NextConsensus` address. This can be an alternative to #14 not requiring additional state storage (`NextConsensus -> set of addresses` mapping) with a very little overhead (40 bytes for 7 nodes, stripping 100 easily).

**Comment by roman-khimov** [comment]
Related to #48.
