### ISSUE TITLE
Encoding-level dBFT Payload verification

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#57]
This issue is somewhat similar to #53, but is about encoding-level checks. Currently (since #49), no encoding-level validity checks is being performed. What we may want to implement (compared to the NeoGo verification experience) is some basic validity/restrictions check for dBFT payloads on decoding stage. For example, add `MaxTransactionsPerBlock` check to PrepareRequest decoder, ref. e43a2298b78683587ca16f14f87499142cdd887b. Some other checks are likely to be added.

**Comment by AnnaShaleva** [comment]
I've precisely checked and compared NeoGo decoding-level dBFT payload verification checks, so the result is the following: additional decoding-level checks are required only for PrepareRequest (`MaxTransactionsPerBlock`) and RecoveryMessage (PrepareRequest field decoding in case of non-nil request).

`MaxTransactionsPerBlock`  constraint doesn't exist in Ethereum, the number of transactions is restricted by `GasLimit` field of `types.Block` and this field is checked via `verifyHeader` API in the `WithVerifyBlock` dBFT callback:
https://github.com/bane-labs/go-ethereum/blob/c83107d9a565a1bba3c5d7ba3d137b287047fff7/consensus/dbft/dbft.go#L767-L770
and
https://github.com/bane-labs/go-ethereum/blob/c83107d9a565a1bba3c5d7ba3d137b287047fff7/consensus/dbft/dbft.go#L819-L822

`RecoveryMessage` check is performed inside the custom RLP decoder:
https://github.com/bane-labs/go-ethereum/blob/c83107d9a565a1bba3c5d7ba3d137b287047fff7/consensus/dbft/recovery_message.go#L226-L229

The rest of payloads don't need to be checked. And thus, this issue may be closed as completed since no additional decoding-level verification checks should be performed. @roman-khimov, agree to close?

**Comment by roman-khimov** [comment]
If we're decoding an array of hashes from `PrepareRequest` and we don't have some `MaxTransactionsPerBlock` --- a rogue Primary could spam us with some high number of transactions. But we have `maxMessageSize` of 4M, so it won't be more than that and this number is likely OK for us. Same goes for recovery (size-wise).

Then RM type is checked and these is nothing else left indeed. OK.
