### ISSUE TITLE
Add testing privnet config and minimal instructions

### ISSUE THREAD

**Issue by roman-khimov** [bane-labs/go-ethereum#8]
See https://geth.ethereum.org/docs/fundamentals/private-network, let's create a minimal config for Clique-enabled consensus, some well-known key (like NeoGo https://github.com/nspcc-dev/neo-go/tree/master/.docker/wallets) and instructions of how to run a "miner" node and connect another one to it. It will be extended with contracts when they're ready and it will be changed to dBFT once it's there. The idea is to have a simple way to get the network up and running for various purposes.

**Comment by roman-khimov** [comment]
All hardforks should be available from the genesis block, of course.

**Comment by doubiliu** [comment]
The preloading contract needs to be configured in the configuration file of the genesis block
 "alloc": {
    "0x0000000000000000000000000000000000000020（contract address）": {
      "code": "606060405236156100c45760e060020a60003504631290948581146100...<opcode>...",
      "storage": {
        "0x0000000000000000000000000000000000000000000000000000000000000001": "0x02",  static variable
        ...
      }
    }
}
These values ​​​​can be obtained through remix. I recommend setting them after governance contract review.
