### ISSUE TITLE
Create loading tool for NeoX network testing

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#88]
# Rationale

Instead of custom transaction loader tool implemented in https://github.com/bane-labs/go-ethereum/pull/81 we need some common JS-based loader that can be used for privnet/testnet NeoX testing. Ref. https://github.com/bane-labs/go-ethereum/pull/81#issuecomment-1871264458.

# Implementation

@nicolegys already has one, we need to make it public and create a basic doc, ref. https://github.com/bane-labs/go-ethereum/pull/81#issuecomment-1871125458. It should be enough for initial privnet load testing. Also, within the scope of this issue we may check for existing Eth loading tools (likely, there are some).

**Comment by nicolegys** [comment]
@AnnaShaleva I used an open source stress-test tool ([pandoras-box](https://github.com/madz-lab/pandoras-box)) in recent tests. It can batch transactions and output an detailed statistics calculation. Do you think we should set up our own tool?

**Comment by roman-khimov** [comment]
I'd try to avoid it as much as possible. If that one is easy to use for everyone and does the job, let's use it and be done with it.

**Comment by AnnaShaleva** [comment]
Good, @nicolegys, thank you for shearing, I tried pandoras-box and it works OK for me. Final question I have for you, do you have any specific stresstesting scenarios for pandoras-box run? Could you share your experience? They have a set of different loading modes like described in https://github.com/madz-lab/pandoras-box#usage-example, which one do you use more frequently?

**Comment by nicolegys** [comment]
> do you have any specific stresstesting scenarios for pandoras-box run? 

@AnnaShaleva I'm sorry not to have any. Since there are some issues with our dbft under high load, I haven't worked out a stress test routine to measure the performance.
The only two things I can share,
1. For mode, `[EOA, ERC20, ERC721]` are selected equally because they cost differect amount of gas. 
2. It seems that `pandoras-box` doesn't check and wait refund txs mined, so the first time you run a task, it may failed with `insufficient funds` filling the screen.

**Comment by AnnaShaleva** [comment]
Good, thank you! Then I'm closing this issue as "not planned" since there's a good existing tool for testing.
