### ISSUE TITLE
Branching point

### ISSUE THREAD

**Issue by roman-khimov** [bane-labs/go-ethereum#9]
We've got `bane-main` branch with 950ccddfc8938b2bf13be5cd350882b6dc568a0b HEAD currently that was taken from the geth's master at some point in time. Which means we're branching off of unstable intermediate development state of some future geth version. I think it's somewhat risky (stability, compatibility) and we better take the latest stable (v1.12.2 IIUC). This will make managing subsequent updates from geth easier as well.

@gsmachado, @steven1227.

**Comment by gsmachado** [comment]
I believe we should target the **next** geth release, which will be released soon. They release frequently.

If we based ourselves on the latest stable (v1.12.2) we would need to merge the next release anyway.

**Comment by gsmachado** [comment]
Moreover, I have also pushed the branch `release/1.12` in this repo. We should keep track of geth releases in `release/`, please.

I suggest to create `bane-release/*` to reflect our own releases.

**Comment by roman-khimov** [comment]
To me it's easier to have some stable ground first and then merge 1.13.0 changes when we're ready to. Because now we are neither 1.12.x-, nor 1.13-compatible. Maybe the commit we have in `bane-main` is completely broken, but we don't know it yet.

**Comment by txhsl** [comment]
@roman-khimov @gsmachado Geth v1.13.0 is now released and marked as [stable](https://github.com/ethereum/go-ethereum/commit/7371b38171b1977ceaec80a86996ed0645aa5b1f#diff-4e24c6d8459e5c7cd21f47243944ed76a37c7445bfa3949f1efd25141bdf7583R27), how about merging it and updating our codes?

**Comment by gsmachado** [comment]
> I believe we should target the **next** geth release, which will be released soon. They release frequently.

Yes, I told 👆 that geth releases frequently. 😄 

@txhsl I'm still in Singapore. Once I get back (Monday), I will update and merge to v1.13.0. 👍 

💪

**Comment by gsmachado** [comment]
@txhsl @roman-khimov done. ✅ 

I just pulled from geth remote two things:
- `release/1.13` branch is now available in this repo.
- `bane-main` branch is now at the same commit of `release/1.13` branch.
